<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AliMun" name="Create PortFolio Test" tests="3" failures="1" timestamp="9 Mar 2016 22:48:07 GMT" time="40.952" errors="0">
  <testcase name="createPortfolio" time="0.009" classname="com.selenium.datadriven.test.CreatePortFolioTest">
    <skipped/>
  </testcase> <!-- createPortfolio -->
  <testcase name="createPortfolio" time="38.016" classname="com.selenium.datadriven.test.CreatePortFolioTest">
    <failure type="java.lang.Throwable" message="Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: Title doesn&amp;apos;t match expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.selenium.datadriven.page.LoginPage.doLogin(LoginPage.java:36)
	at com.selenium.datadriven.util.Utility.logIn_Application(Utility.java:87)
	at com.selenium.datadriven.test.CreatePortFolioTest.createPortfolio(CreatePortFolioTest.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
nnFailure 2 of 2:njava.lang.NullPointerException">
      <![CDATA[java.lang.Throwable: Multiple failures (2):nnFailure 1 of 2:njava.lang.AssertionError: Title doesn't match expected [true] but found [false]
	at com.selenium.datadriven.page.LoginPage.doLogin(LoginPage.java:36)
	at com.selenium.datadriven.util.Utility.logIn_Application(Utility.java:87)
	at com.selenium.datadriven.test.CreatePortFolioTest.createPortfolio(CreatePortFolioTest.java:35)
nnFailure 2 of 2:njava.lang.NullPointerException
	at com.selenium.datadriven.test.CreatePortFolioTest.createPortfolio(CreatePortFolioTest.java:55)
... Removed 51 stack frames]]>
    </failure>
  </testcase> <!-- createPortfolio -->
  <testcase name="createPortfolio" time="0.0" classname="com.selenium.datadriven.test.CreatePortFolioTest">
    <skipped/>
  </testcase> <!-- createPortfolio -->
</testsuite> <!-- Create PortFolio Test -->
